### ISSUE TITLE
How about a "CodeCorp" Gitter Channel?

### ISSUE THREAD

**Issue by ashutoshsaboo** [CodeCorp/Utilities#1]
We can create our Gitter channel here - https://gitter.im for communication purposes, in case if everyone is fine?

It'll help us in discussing / communicating about some project, in case if we work in teams on that project?

How about it?

**Comment by rohangoel96** [comment]
We don't have many people actively working on projects currently so it won't be of much use at the moment but this is a nice idea. Hence I have created the channel at https://gitter.im/CodeCorp.

Thanks, @ashutoshsaboo for the idea.
