### ISSUE TITLE
Let's add a LICENSE to all the repos under CodeCorp

### ISSUE THREAD

**Issue by ashutoshsaboo** [CodeCorp/Utilities#3]
MIT License (http://choosealicense.com/licenses/mit/) seems to be the best for us - http://choosealicense.com/ . So, that even if someone takes our code, then he must provide us attribution back. 

I have created a License file already. Do let me know if it's fine? 

How about it?

**Comment by rohangoel96** [comment]
I guess we should ensure that whenever someone uses our code, CodeCorp should be attributed?

**Comment by ashutoshsaboo** [comment]
Yes. Now check the updated License and readme files. Added the CodeCorp name adjacent to the copyright symbol. :+1:

**Comment by ashutoshsaboo** [comment]
Closing issue for now. If anyone has any issues, feel free to raise issue.
